/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.ts' */

export = {
  plugins: ["prefer-named-export"],
  rules: {
    "prefer-named-export/prefer-named-export": "error"
  },
};
