import fs from 'fs';
import { ESLint } from 'eslint';
import { pluginId } from './plugin-id';
import { rules } from './rules';
import { resolvePath } from '@/scripts/lib/resolve-path';

const filePath = resolvePath('@/src/configs/recommended.ts');
const rawContent = `/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.ts' */

export = {
  plugins: ["${pluginId}"],
  rules: {
    ${rules
      .filter((rule) => rule.recommended)
      .map((rule) => `"${rule.id}": "error"`)
      .join(',\n    ')}
  },
};
`;

(async () => {
  const engine = new ESLint({ fix: true });
  const lintResults = await engine.lintText(rawContent, { filePath });
  const content = lintResults[0].output || rawContent;

  fs.writeFileSync(filePath, content);
})();
