import fs from 'fs';
import path from 'path';
import { ESLint } from 'eslint';
import { rules } from './rules';

const filePath = path.resolve(__dirname, '../../src/index.ts');
const rawContent = `/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */

export = {
  configs: {
    recommended: import("./configs/recommended"),
  },
  rules: {
    ${rules
      .map((rule) => `"${rule.name}": import("./rules/${rule.name}")`)
      .join(',\n    ')}
  },
};
`;

(async () => {
  const engine = new ESLint({ fix: true });
  const lintResults = await engine.lintText(rawContent, {filePath});
  const content = lintResults[0].output || rawContent;
  
  fs.writeFileSync(filePath, content);
})()
