/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */

export = {
  configs: {
    recommended: require('./configs/recommended'),
  },
  rules: {
    'prefer-named-export': require('./rules/prefer-named-export'),
  },
};
