/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */

export = {
  configs: {
    recommended: import("./configs/recommended"),
  },
  rules: {
    "prefer-named-export": import("./rules/prefer-named-export")
  },
};
